//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPRESA
    {
        public int ID_EMPRESA { get; set; }
        public string NOMBRE_COMERCIAL { get; set; }
        public string RUC { get; set; }
        public string NOMBRE_RESPONSABLE { get; set; }
        public string DIRECCION { get; set; }
        public string TELEFONO { get; set; }
        public string EMAIL { get; set; }
        public string ACTIVIDAD_ECONOMICA { get; set; }
        public string AUTORIZACION_SRI { get; set; }
    }
}
