//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROL_OPERACION
    {
        public int ID_ROL_OPERACION { get; set; }
        public int USUARIO_ID { get; set; }
        public int OPERACION_ID { get; set; }
        public bool ESTADO { get; set; }
    
        public virtual OPERACION OPERACION { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
