//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSACCION_REAL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRANSACCION_REAL()
        {
            this.FACTURA = new HashSet<FACTURA>();
            this.REG_DET_LIBROS = new HashSet<REG_DET_LIBROS>();
        }
    
        public int ID_TRANS_REAL { get; set; }
        public int RUB_ID { get; set; }
        public int FACTURA_ID { get; set; }
        public bool TIPO { get; set; }
        public System.DateTime FECHA { get; set; }
        public decimal SUBTOTAL { get; set; }
        public decimal IMPUESTO { get; set; }
        public decimal TOTAL { get; set; }
        public int USU_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACTURA> FACTURA { get; set; }
        public virtual FACTURA FACTURA1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REG_DET_LIBROS> REG_DET_LIBROS { get; set; }
        public virtual RUBRO RUBRO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
